DROP DATABASE IF EXISTS burger_db;
CREATE DATABASE burger_db;
USE burger_db;

CREATE TABLE burgers (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(100),
isDevoured BOOLEAN NOT NULL DEFAULT 0,
PRIMARY KEY(id)
);